on: [push, pull_request]
name: ShellCheck
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shellcheck
      uses: ludeeus/action-shellcheck@0.0.1
      with:
        args: openvpn-install.sh -e SC1091,SC2164,SC2034,SC1072,SC1073,SC1009
